version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=115
      - TZ=Europe/Madrid
    volumes:
      - /path/config:/config
      - /path/series:/data/tvseries
      - /path/downloads:/downloads

    ports:
      - 8989:8989
    restart: unless-stopped